# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [12]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [8]:
# your code here
print(np.version.version)

1.19.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [61]:
# Method 1  --> Integer between numbers define (being lowest Zero by default), can define size (or not)
a=np.random.randint(100,size=(2,3,5))

In [62]:
# Method 2 -->  Populates with samples from a uniform distribution over [0, 1) (they type is float)
a=np.random.rand(2,3,5)   #each argument represents a part of the size

In [63]:
# Method 3  --> Returns random floats in the half-open interval [0.0, 1.0)
a=np.random.ranf((2,3,5))      #just takes one argumet so size need to be in parêntesis

In [64]:
#Other --> https://docs.scipy.org/doc//numpy-1.14.0/reference/routines.random.html

#### 4. Print *a*.


In [65]:
# your code here
a

array([[[0.81654951, 0.29684034, 0.8377357 , 0.50612759, 0.10424137],
        [0.01043203, 0.08686476, 0.91525394, 0.59884363, 0.37086566],
        [0.92879322, 0.22369756, 0.63897708, 0.21018769, 0.17356049]],

       [[0.63403854, 0.559426  , 0.51638855, 0.15113284, 0.22021606],
        [0.0391053 , 0.13800544, 0.31714694, 0.3769959 , 0.23062361],
        [0.14741155, 0.21381673, 0.22589677, 0.43075103, 0.68374868]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [77]:
# your code here
b=np.ones((5,2,3))

In [44]:
#Method 2
b=np.full((5,2,3),1)

#### 6. Print *b*.


In [78]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [70]:
# your code here
print(a.shape==b.shape)
print("They don't have the same size")

False
They don't have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [74]:
# your answer here
print("As the error says we can't sum arrays with different shapes")
junto=a+b
junto

As the error says we can't sum arrays with different shapes


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [84]:
# your code here
c=np.transpose(b, (1,2,0))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [86]:
# your code/answer here
d=a+c
print("it works because the aarays have the same shape and so are in a sense compatible")

it works because the aarays have the same shape and so are in a sense compatible


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [96]:
# your code/answer here
print("a:",a,"\nd:",d,"\ndifference:",(d-a))
print("B\c d is the result of c+a, being c an array with only the number one it makes sense that d vary from a in one unit")

a: [[[0.81654951 0.29684034 0.8377357  0.50612759 0.10424137]
  [0.01043203 0.08686476 0.91525394 0.59884363 0.37086566]
  [0.92879322 0.22369756 0.63897708 0.21018769 0.17356049]]

 [[0.63403854 0.559426   0.51638855 0.15113284 0.22021606]
  [0.0391053  0.13800544 0.31714694 0.3769959  0.23062361]
  [0.14741155 0.21381673 0.22589677 0.43075103 0.68374868]]] 
d: [[[1.81654951 1.29684034 1.8377357  1.50612759 1.10424137]
  [1.01043203 1.08686476 1.91525394 1.59884363 1.37086566]
  [1.92879322 1.22369756 1.63897708 1.21018769 1.17356049]]

 [[1.63403854 1.559426   1.51638855 1.15113284 1.22021606]
  [1.0391053  1.13800544 1.31714694 1.3769959  1.23062361]
  [1.14741155 1.21381673 1.22589677 1.43075103 1.68374868]]] 
difference: [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
B\c d is the result of c+a, being c an array with only the number one it makes sense that d vary from a in one unit


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [99]:
# your code here
e=a*c
e

array([[[0.81654951, 0.29684034, 0.8377357 , 0.50612759, 0.10424137],
        [0.01043203, 0.08686476, 0.91525394, 0.59884363, 0.37086566],
        [0.92879322, 0.22369756, 0.63897708, 0.21018769, 0.17356049]],

       [[0.63403854, 0.559426  , 0.51638855, 0.15113284, 0.22021606],
        [0.0391053 , 0.13800544, 0.31714694, 0.3769959 , 0.23062361],
        [0.14741155, 0.21381673, 0.22589677, 0.43075103, 0.68374868]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [100]:
# your code/answer here
print(a==e)
print("They are the same, b\c e is the result of multiplying the value in a for 1")

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
They are the same, b\c e is the result of multiplying the value in a for 1


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [145]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()
print(d_max, d_min,d_mean)

1.9287932206433371 1.0104320294658138 1.386789151047812


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [191]:
# your code here
f=np.empty([2,3,5],dtype=int)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [189]:
# your code here
for index1 in range(2):
    for index2 in range(3):
        for index3 in range(5):
            if d[index1][index2][index3]==d_min:
                f[index1][index2][index3]=0
            if d[index1][index2][index3]==d_max:
                f[index1][index2][index3]=100
            if d[index1][index2][index3]==d_mean:
                f[index1][index2][index3]=50
            if (d[index1][index2][index3]<d_max and d[index1][index2][index3]>d_mean):
                f[index1][index2][index3]=75
            if (d[index1][index2][index3]>d_min and d[index1][index2][index3]<d_mean):
                f[index1][index2][index3]=25

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [188]:
# your code here
print("d:",d,"\nf:",f)


d: [[[1.81654951 1.29684034 1.8377357  1.50612759 1.10424137]
  [1.01043203 1.08686476 1.91525394 1.59884363 1.37086566]
  [1.92879322 1.22369756 1.63897708 1.21018769 1.17356049]]

 [[1.63403854 1.559426   1.51638855 1.15113284 1.22021606]
  [1.0391053  1.13800544 1.31714694 1.3769959  1.23062361]
  [1.14741155 1.21381673 1.22589677 1.43075103 1.68374868]]] 
f: [[[ 75  25  75  75  25]
  [  0  25  75  75  25]
  [100  25  75  25  25]]

 [[ 75  75  75  25  25]
  [ 25  25  25  25  25]
  [ 25  25  25  75  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [200]:
# your code here
f=np.empty([2,3,5],dtype=str)
for index1 in range(2):
    for index2 in range(3):
        for index3 in range(5):
            if d[index1][index2][index3]==d_min:
                f[index1][index2][index3]="A"
            if d[index1][index2][index3]==d_max:
                f[index1][index2][index3]="E"
            if d[index1][index2][index3]==d_mean:
                f[index1][index2][index3]="C"
            if (d[index1][index2][index3]<d_max and d[index1][index2][index3]>d_mean):
                f[index1][index2][index3]="D"
            if (d[index1][index2][index3]>d_min and d[index1][index2][index3]<d_mean):
                f[index1][index2][index3]="B"
f

array([[['D', 'B', 'D', 'D', 'B'],
        ['A', 'B', 'D', 'D', 'B'],
        ['E', 'B', 'D', 'B', 'B']],

       [['D', 'D', 'D', 'B', 'B'],
        ['B', 'B', 'B', 'B', 'B'],
        ['B', 'B', 'B', 'D', 'D']]], dtype='<U1')